revised solution for tasks 0

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,9 @@
 #!/bin/bash
+
+# Check if the $PYFILE enviroment variable is set
+    if [ -z "$PYFILE"]; then
+     echo "Error: Enviroment variable  \$PYFILE is not set."
+     exit 1
+    fi
+
 python3 ./$PYFILE
